# Site settings
title: BreadWiki
url: "https://wiki.junbread.win"
baseurl: ""
description: >
    personal develop note wiki

# My information
email: me@junbread.win
author: Junbread
profile: 
twitter_username: 
github_username: junbread
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id:
  shortname:
utterances:
  repo: junbread/wiki
  issue-term: pathname
  label: comment
  branch: master

google_analytics:
  ua: UA-167309833-2
google_adsense:
  client:

blame: "https://github.com/junbread/wiki/blame/master/_wiki"
edit: "https://github.com/junbread/wiki/edit/master/_wiki"
issue: "https://github.com/junbread/wiki/issues/new"

timezone: "Asia/Seoul"
